logging:
  level:
    root: INFO
    web: DEBUG

spring:
  config:
    activate:
      on-profile: development

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./taskManager
    username:
    password:

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
