logging:
  level:
    root: INFO

spring:
  config:
    activate:
      on-profile: production

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}

  jpa:
    show-sql: true