server:
  port: ${PORT:5000}

base-url: /api

spring:

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    enabled: true

jwt:
  secret: 5368566D597133743677397A24432646294A404E635266556A576E5A72347537

rollbar:
  token: cb66aa54c4494b0591ea3df0be5b9e07