server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    url: ${MYSQL_URL}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    enabled: true
