name: JAVA CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Print Rollbar token
        env:
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
        run: echo $ROLLBAR_TOKEN

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.1.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco